language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

script:
  - |
    if [[ $PHP = 5.4.* || $PHP = 5.5.* ]]; then
      ./vendor/bin/phpunit-4.8
    else
      ./vendor/bin/phpunit
    fi